/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
// Where is the LED connected?
// GPIO Port: A
// Pin: 5
//
// Open Data sheet
// Look at peripheral memory mapping
//
// BUS mapping:
// GPIO port a is touching AHB1
// We need to go through AHB1 to supply clock to GPIO port a
#include <stdint.h>
#include <stdio.h>
#include "stm32f446xx.h"
#include "uart.h"
#include "NucleoFpga.h"

char key;

int main(void)
{
  uart2_rxtx_init();
  
  RCC->AHB1ENR |= GPIOAEN;
  GPIOA->MODER |= (1U<<10);
  GPIOA->MODER &=~ (1U<<11);
  while(1)
  {
    // Non-blocking read: only read if data is available
    if(USART2->SR & SR_RXNE) {
      key = uart2_read();
    }
    
    // Blink LED when key is '1'
    if(key == '1'){
      GPIOA->ODR |= LED_PIN;
      for(volatile int i = 0; i < 1000000; i++); // Delay
      GPIOA->ODR &=~ LED_PIN;
      for(volatile int i = 0; i < 1000000; i++); // Delay
    } else if(key == '0') {
      GPIOA->ODR &=~ LED_PIN;
    }
  }
  return 0;
}
