/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
// Where is the LED connected?
// GPIO Port: A
// Pin: 5
//
// Open Data sheet
// Look at peripheral memory mapping
//
// BUS mapping:
// GPIO port a is touching AHB1
// We need to go through AHB1 to supply clock to GPIO port a
#include <stdint.h>
#include <stdio.h>
#include "NucleoFpga.h"
#include "stm32f446xx.h"

int main(void)
{
  // Enable clock access to GPIOA
  RCC->AHB1ENR |= GPIOAEN;
  RCC->AHB1ENR |= GPIOCEN;

  // Set PA5 as output
  // Set bit 10 high
  // Set bit 11 low
  GPIOA->MODER |= (1U<<10);
  GPIOA->MODER &=~ (1U<<11);

  GPIOC->MODER &=~ (1U<<26);
  GPIOC->MODER &=~ (1U<<27);

  while (1) {
    if(GPIOC->IDR & BTN_PIN){
      GPIOA->BSRR = LED_PIN;
    }
    else{
      GPIOA->BSRR = LED_PIN_RESET;
    }
  }
  return 0;
}
